packages:
  - apps/*
  - packages/*

catalog:
  '@ai-sdk/google': ^2.0.13
  '@orpc/client': ^1.10.0
  '@orpc/openapi': ^1.10.0
  '@orpc/server': ^1.10.0
  '@orpc/zod': ^1.10.0
  ai: ^5.0.49
  dotenv: ^17.2.2
  hono: ^4.8.2
  tsdown: ^0.15.5
  typescript: ^5.8.2
  zod: ^4.1.11

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
